# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
markdown: rdiscount
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path: /atom.xml

production_url : http://bookwyrm.github.com # or your custom domain name
title : Exploring Code

author :
  name : Matt Vanderpol
  email : matt@vanderpol.net
  github : bookwyrm
  twitter : bookwyrm
  # feedbuder : feedname

exclude: .rbenv-version
